spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EnocaDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update